/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scalereader;

import Beans.Users;
import com.formdev.flatlaf.FlatDarculaLaf;
import dao.DaoFactory;
import dao.UserDao;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author ali
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    DaoFactory daoFactory = DaoFactory.getInstance();
    UserDao userdao=daoFactory.getUserDao();
    String f;
    public Login() {
        initComponents();
        erreur.setVisible(false);
        this.setLocationRelativeTo(null);
        ItemListener listener = new ItemListener() {
         public void itemStateChanged(ItemEvent e) {
            if (e.getSource() == admin && admin.isSelected()) {
                f="admin";
               vendeur.setSelected(false);
            } else if (e.getSource() == vendeur && vendeur.isSelected()) {
                f="vendeur";
               admin.setSelected(false);
            }
         }
        };

        admin.addItemListener(listener);
        vendeur.addItemListener(listener);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        admin = new javax.swing.JCheckBox();
        pwd = new javax.swing.JPasswordField();
        vendeur = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();
        erreur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Authentification");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 330, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setText("NOM D'UTILISATEUR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("MOT DE PASSE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        admin.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        admin.setForeground(new java.awt.Color(255, 255, 255));
        admin.setText("Administrateur");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jPanel1.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        pwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 175, 330, 50));

        vendeur.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        vendeur.setForeground(new java.awt.Color(255, 255, 255));
        vendeur.setText("Vendeur");
        vendeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendeurActionPerformed(evt);
            }
        });
        jPanel1.add(vendeur, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        loginButton.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        loginButton.setText("S'authentifier");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 312, 150, 52));

        erreur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        erreur.setForeground(new java.awt.Color(255, 255, 0));
        erreur.setText("Login et/ou mot de passe est incorrecte !!");
        jPanel1.add(erreur, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 280, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void vendeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendeurActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(admin.isSelected())
            f="admin";
        if(vendeur.isSelected())
            f="vendeur";
        if(userdao.connexionSucceeded(login.getText(), new String(pwd.getPassword()),f)){
            Users.setInstance(userdao.connectedUser(login.getText(), new String(pwd.getPassword()),f));
            if(Users.getInstance().getFonction().equals("admin")){
                new Administration().setVisible(true);
                this.dispose();}
            else {
                new Main().setVisible(true);
                this.dispose();
            }
        }else
            erreur.setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarculaLaf.registerCustomDefaultsSource("style");
        FlatDarculaLaf.setup();
        //        IntelliJTheme.setup(Main.class.getResourceAsStream("/template.theme.json"));

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox admin;
    private javax.swing.JLabel erreur;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField login;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JCheckBox vendeur;
    // End of variables declaration//GEN-END:variables
}
